---
title: "Untitled"
author: "Erin C Rooney"
date: "5/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      comment = "#>",
                      fig.path = ("markdown-figs/doc/"))
#source("code/0-packages.R")
library(drake)
```

## R Markdown
### Phosphorus Availability
#### Cover Crops and Compost
#### May 26 2021

## RELABUND PLOTS
```{r relabund, fig.width=8, echo=FALSE}
readd(phos_relabund)
```

```{r relabund_boxplot, fig.width=8, echo=FALSE}
readd(phos_relabund_boxplot)
```

## PHOSPHORUS (ABSOLUTE) PLOTS

#### Available P  
```{r available_p_point, fig.width=5, fig.height = 6, echo=FALSE}
readd(available_p_point)
```

#### Reserve P  
```{r reserve_p_point, fig.width=5, fig.height = 6, echo=FALSE}
readd(reserve_p_point)
```

#### Organic P  
```{r organic_p_point, fig.width=5, fig.height = 6, echo=FALSE}
readd(organic_p_point)
```

#### Unavailable P  
```{r unavailable_p_point, fig.width=5, fig.height = 6, echo=FALSE}
readd(unavailable_p_point)
```

#### Available P separated by Time 1 and 2 (greenhouse rotations) 
#### TIME 1
```{r t1_available_p_point, fig.width=5, fig.height = 6, echo=FALSE}
readd(t1_available_p_point)
```

#### TIME 2
```{r t2_available_p_point, fig.width=5, fig.height = 6, echo=FALSE}
readd(t2_available_p_point)
```

#### Reserve P separated by Time 1 and 2 (greenhouse rotations) 
#### TIME 1
```{r t1_reserve_p_point, fig.width=5, fig.height = 6, echo=FALSE}
readd(t1_reserve_p_point)
```

#### TIME 2
```{r t2_reserve_p_point, fig.width=5, fig.height = 6, echo=FALSE}
readd(t2_reserve_p_point)
```